stages:
  - build
  - test
  - dockerize

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

run in prod-like env:
  image: node:13-alpine3.11
  stage: build
  script:
    - sh
    - echo "$CI_ENV" > config.env
    - apk add coreutils
    - timeout --preserve-status 60s node .

run unit tests:
  image: node:13-alpine3.11
  only:
    - master
    - 2-ci-cd-pipeline
  stage: test
  script:
    - sh
    - echo "$CI_ENV" > config.env
    - echo "$CI_ENV" > .test.env
    - npm run test
