image: node:13-alpine3.10

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline
    
run unit tests:
  only: master
  stage: test
  script:
    - npm run test
