stages:
  - build
  - test
  - dockerize

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

before_script:
  - npm i

run in local env:
  image: node:13-alpine3.11
  stage: build
  script:
    - bash
    - echo "$TEST_ENV" > config.env
    - timeout --preserve-status 60s node .

run unit tests:
  image: node:13-alpine3.11
  only:
    - master
    - 2-ci-cd-pipeline
  stage: test
  script:
    - echo "$TEST_ENV" > config.env
    - npm run test